### ISSUE TITLE
Adding Keyboards

### ISSUE THREAD

**Issue by dwhacks** [oyzzo/MemTypeTool#10]
Its says on hackaday.io "Easy to generate keymaps, edit the example file and generate the one for your keyboard map and language."
How do we do this?

**Comment by oyzzo** [comment]
The keymap file is a list of keycodes where the position corresponds to the ascii code number. So for example, the keycode corresponding to the ASCII 97 is the integer on the 97th position on the list.

We should document it. There is a python tool and a special firmware on it's own branch that autogenerates that files, so while the documentation is being made everyone can ask for any keymap file and we'll upload it to the keyboards dir on the git.
