### ISSUE TITLE
Add encryption for export/import file

### ISSUE THREAD

**Issue by drtrigon** [oyzzo/MemTypeTool#12]
I need a way to securely store/backup the passwords encrypted too. Thus I would like to propose to add e.g. GPG encryption or any other suitable method to the export and import file buttons.

**Comment by oyzzo** [comment]
Hi @drtrigon  you're right, encrypted export would be so useful.
An AES encryption option for the exported file could be good option for example.
What do you think? Using a different stronger password could be the best choice?
Meanwhile it's easy to encrypt the resulting file using openssl command.

**Comment by drtrigon** [comment]
I'd like to avoid having the data stored unencrypted in any place, thus encrypt immediately and before storing.
I do not have oppionions on algprithms as long as its free/open (like GPG) and strong. In case of GPG the password is already given.
Using openssl do you have a concrete command line in mind?

**Comment by oyzzo** [comment]
You're right about storing unencrypted data, that feature is high priority and will be implemented ASAP. 
As a workaround while it's being implemented both GPG and openssl are opensource and can be used to encrypt the file using AES256 algorythm. 
The GPG command for encrypting:
gpg --output encrypted.data --symmetric --cipher-algo AES256 un_encrypted.data
And for decrypting:
gpg --output un_encrypted.data --decrypt encrypted.data

A prompt asking for a password will appear.

**Comment by oyzzo** [comment]
The AES encryption export and import is being implemented into the develop branch.
For the moment the export part is already working and the import part is on the way right now.

**Comment by drtrigon** [comment]
Sorry for not coming back until now; please, can you notify me when the import is working too, such that I can test it for you (and me) and report back?

Just tested and it works for me - nice and thanks!!

**Comment by oyzzo** [comment]
@drtrigon sure! it's already working on master branch :)

Check it and let us know if there's any issue!

Thanks to you!
