### ISSUE TITLE
MemType device not found

### ISSUE THREAD

**Issue by ec1oud** [oyzzo/MemTypeTool#13]
I tried on Ubuntu 16.04, Arch, and OS X.  I get the same error on all of them.

**Comment by jim17** [comment]
Hello, in UBUNTU try to execute it as sudo or give it USB permissions.

**Comment by oyzzo** [comment]
Hi @ec1oud, does the "lsusb" command in linux or the "system information" in OS X show the memtype device?
If it does, have you installed libusb-dev as well as pyusb?
