### ISSUE TITLE
Don't like @ with french keymap

### ISSUE THREAD

**Issue by Foul** [oyzzo/MemTypeTool#14]
Display ä instead of @

**Comment by oyzzo** [comment]
Is it still happening? or it was resolved by rewritting the keyboard layout.
on windows, linux  & macOS? or just one of them.

**Comment by Foul** [comment]
still happening...

**Comment by oyzzo** [comment]
Ok, I'll test the keyboard layout file to check if there's something wrong there with the keycodes or it's a firmware bug.

**Comment by oyzzo** [comment]
Hi @Foul , can you try this new French keyboard layout?

I think the old one had a problem on some keycodes. It seems to work OK for me now :)

[keyboard_FR.txt](https://github.com/oyzzo/MemTypeTool/files/786223/keyboard_FR.txt)

**Comment by Foul** [comment]
Working perfect ! thx :)
