### ISSUE TITLE
MemType device not found!

### ISSUE THREAD

**Issue by Qu13t** [oyzzo/MemTypeTool#16]
I'm using Gnome and I just got the GUI to work, however whenever I try to write or read anything from the MemType it gives me an error: "MemType device not found!". The device is on it writes to text window and is unlocked but for some reason it still won't read or write. I saw a similar issue already addressed but it didn't seem to be resolved despite being closed. You can't run it as sudo all you get is a blank grey screen and errors.

**Comment by oyzzo** [comment]
Hi @Qu13t !

Thanks for your feedback!

Is there any other error or warning message in the terminal where you opened the GUI?
Are all the dependencies installed? (libusb) (pyusb)
Does it happen the same when executing as root? (sudo)
Can you attach a dmesg log? ($dmesg > log.txt)

**Comment by Qu13t** [comment]
You can't run it as root. When you do so the GUI only shows a grey screen.
