### ISSUE TITLE
Disable pins longer the 4 digits

### ISSUE THREAD

**Issue by aminehmida** [oyzzo/MemTypeTool#17]
I have changed the pin to something longer then 4 digits and it is now locked and unable to accept more the 4 digits.

**Comment by oyzzo** [comment]
Hi @aminehmida !

if your memtype firmware version is 3.2.0 you can enter any wrong PIN 4 times and you'll get a special PIN ERR message indicating the PIN has been reset to '0000'.

Setting PIN longer than 4 is a bug in the MemTypeTool Python GUI. We're close to release a new GUI that solves this and other issues.
You can follow the progress under the "rewrite" branch.
