### ISSUE TITLE
Memory corruption when trying to read 2 or more entries

### ISSUE THREAD

**Issue by Jens70** [oyzzo/MemTypeTool#22]
I can read and write one entry, but not two, then I get:

*** Error in `/home/jens/linux64/./MemTypeManager': malloc(): memory corruption: 0x000055f15de96500 ***
Followed by a whole lot of rows.

Even if I can only read one entry, I can write many. The test is performed on Mint 18.1 with credentials that only uses a-z, \t, \n. I have tried with two different sticks sticks. The software used is from the precompiled folder linux64.

**Comment by Jens70** [comment]
I now notice, that when I used set keylayout it works. without errors. I don't know how the keylayout thing works, but both of my sticks have been used in another computer where I have used the set keylayout function, but in this computer it had newer been used before I did it now, and now everything works.

**Comment by oyzzo** [comment]
Great, I'll look into this "First Use" issue, as it may be related to the firmware.

Thanks!
