### ISSUE TITLE
New credentials dialog appears behind mainWindow

### ISSUE THREAD

**Issue by Jens70** [oyzzo/MemTypeTool#23]
Sometimes When pressing the "+" icon,  no dialog appears. IT turns out that it is hidden behind mainWindow. Restarting the software does not help. The dialog will not appear in front of the mainWindow until it is moved there manually, but after that it will stay in front even when restarting the software. This is not a great issue, but it took me some time to figure out the first time it happened.

**Comment by oyzzo** [comment]
Hi @Jens70 !

What version are you using?
There is a deprecated Python version that is no longer supported, if that's the case try using the new version 1.0, it was rewritten from scratch in C++ Qt5.8 and has lots of improvements :)
