### ISSUE TITLE
Crashes as soon as it finishes reading (Ubuntu 16.04)

### ISSUE THREAD

**Issue by arielbeje** [oyzzo/MemTypeTool#25]
I enter the correct pin, click on the read button, it goes up to 99% and crashes, with this error message:

`*** Error in /home/user/Downloads/MemTypeTool/release/linux64/./MemTypeManager': malloc(): memory corruption (fast): 0x00005628592ae500 ***`

I got the linux64 folder by doing `tar xvfz MemTypeTool-1.0.0-linux_x64.tar.gz`, and I ran MemTypeManager.sh

**Comment by dgouramanis** [comment]
I have the same problem running Archlinux 64 bit. The program exits instantly upon reading the device. The terminal message is below. 

`/usr/lib/libm-2.25.so./MemTypeManager.sh: line 15: 17213 Aborted                 (core dumped) $dirname/$appname "$@`

**Comment by oyzzo** [comment]
hi @arielbeje  and @dgouramanis 

Sorry for the late reply. The bug it's been fixed and a new binary release for 64 and 32 bit linux has been deployed in:
https://github.com/oyzzo/MemTypeTool/releases

Thanks for your feedback!
