### ISSUE TITLE
Windows compilation

### ISSUE THREAD

**Issue by Yury-MonZon** [oyzzo/MemTypeTool#26]
I'm trying to follow your build instructions but I'm stuck at:
https://ibb.co/ictsYw
https://ibb.co/cN4zDw

What do I do next?

**Comment by oyzzo** [comment]
I think you have installed Qt creator but, you need a C++ compiler in order for it to work.

We don't have windows, so we have never compiled it in windows, we don't know for sure if it works on windows.

The only version of the GUI that we've used in windows is the Python version, so I'd recommend first installing the python version, and when you've got it to work, try the C++ version:
https://github.com/oyzzo/MemTypeTool/archive/0.5.zip
http://www.area0x33.com/documentation/memtype.html#_memtypetool_gui

If you want to try the C++ version in Windows, the first step is to compile the GUI using qt creator, you've installed it but I think there's no build target configured, a quick search in google reveals that it can be installed with Visual C++ or with MinGW g++ compiler.

If you get it working in windows it'd be very nice if you can provide us with the binaries for others to download, or the steps you followed to compile the C++ version.

**Comment by Yury-MonZon** [comment]
I'm still trying to do it =) Now I'm stuck at memtype_ret_t definition
https://ibb.co/gKfUgG

UPD: I've passed that part, but got stuck at not detecting libusb library.

I guess this is not possible for me, I've never tried anything Qt related.
Anyone else could try it?
